#ifndef GUI_LANG_H
#define GUI_LANG_H

#define LANG_MENU_MAIN_TITLE                                          1
#define LANG_MENU_MAIN_OSD_PARAM                                      2
#define LANG_MENU_MAIN_SCRIPT_PARAM                                   3
#define LANG_MENU_MAIN_VISUAL_PARAM                                   4
#define LANG_MENU_MAIN_MISC                                           5
#define LANG_MENU_MAIN_DEBUG                                          6
#define LANG_MENU_MAIN_RESET_OPTIONS                                  7
#define LANG_MENU_BACK                                                8
#define LANG_MENU_RAW_SAVE                                            9
#define LANG_MENU_PERIOD_TEN_MSEC_COUNT                              10
#define LANG_MENU_OSD_TITLE                                          11
#define LANG_MENU_OSD_SHOW_STATES                                    12
#define LANG_MENU_OSD_SHOW_MISC_VALUES                               13
#define LANG_MENU_OSD_ZOOM_VALUE                                     14
#define LANG_MENU_OSD_SHOW_CLOCK                                     15
#define LANG_MENU_OSD_LAYOUT_EDITOR                                  16
#define LANG_MENU_OSD_BATT_PARAMS                                    17
#define LANG_MENU_HISTO_SHOW                                         18
#define LANG_MENU_HISTO_LAYOUT                                       19
#define LANG_MENU_HISTO_MODE                                         20
#define LANG_MENU_HISTO_EXP                                          21
#define LANG_MENU_CALC_SUBMEN_TITLE                                  22
#define LANG_MENU_CALC                                               23
#define LANG_MENU_PLAYBACK_SUBMEN_TITLE                              24
#define LANG_MENU_PLAYBACK                                           25
#define LANG_MENU_ZEBRA_MODE                                         26
#define LANG_MENU_ZEBRA_UNDER                                        27
#define LANG_MENU_ZEBRA_OVER                                         28
#define LANG_MENU_ZEBRA_RESTORE_SCREEN                               29
#define LANG_MENU_ZEBRA_RESTORE_OSD                                  30
#define LANG_MENU_ZEBRA_DRAW_OVER                                    31
#define LANG_MENU_SCRIPT_TITLE                                       32
#define LANG_MENU_SCRIPT_LOAD                                        33
#define LANG_MENU_SCRIPT_DELAY                                       34
#define LANG_MENU_VIS_TITLE                                          35
#define LANG_MENU_VIS_LANG                                           36
#define LANG_MENU_VIS_OSD_FONT                                       37
#define LANG_MENU_VIS_MENU_FONT                                      38
#define LANG_MENU_MISC_TITLE                                         39
#define LANG_MENU_MISC_FILE_BROWSER                                  40
#define LANG_MENU_MISC_TEXT_READER                                   41
#define LANG_MENU_MISC_SHOW_SPLASH                                   42
#define LANG_MENU_MISC_ZOOM_FOR_MF                                   43
#define LANG_MENU_MISC_ALT_BUTTON                                    44
#define LANG_MENU_DEBUG_TITLE                                        45
#define LANG_MENU_DEBUG_SHOW_PROPCASES                               46
#define LANG_MENU_DEBUG_PROPCASE_PAGE                                47
#define LANG_MENU_DEBUG_SHOW_MISC_VALS                               48
#define LANG_MENU_BATT_TITLE                                         49
#define LANG_MENU_BATT_VOLT_MAX                                      50
#define LANG_MENU_BATT_VOLT_MIN                                      51
#define LANG_MENU_BATT_STEP_25                                       52
#define LANG_MENU_READ_TITLE                                         53
#define LANG_MENU_READ_OPEN_NEW                                      54
#define LANG_MENU_READ_OPEN_LAST                                     55
#define LANG_MENU_READ_SELECT_FONT                                   56
#define LANG_MENU_READ_CODEPAGE                                      57
#define LANG_MENU_READ_WORD_WRAP                                     58
#define LANG_MENU_READ_AUTOSCROLL                                    59
#define LANG_MENU_READ_AUTOSCROLL_DELAY                              60
#define LANG_MSG_RESET_OPTIONS_TITLE                                 61
#define LANG_MSG_RESET_OPTIONS_TEXT                                  62
#define LANG_STR_FILE_BROWSER                                        63
#define LANG_STR_SELECT_SCRIPT_FILE                                  64
#define LANG_STR_SELECT_TEXT_FILE                                    65
#define LANG_STR_SELECT_FONT_FILE                                    66
#define LANG_STR_SELECT_LANG_FILE                                    67
#define LANG_MBOX_BTN_OK                                             68
#define LANG_MBOX_BTN_YES                                            69
#define LANG_MBOX_BTN_NO                                             70
#define LANG_MBOX_BTN_CANCEL                                         71
#define LANG_OSD_LAYOUT_EDITOR_HISTO                                 72
#define LANG_OSD_LAYOUT_EDITOR_DOF_CALC                              73
#define LANG_OSD_LAYOUT_EDITOR_STATES                                74
#define LANG_OSD_LAYOUT_EDITOR_MISC                                  75
#define LANG_OSD_LAYOUT_EDITOR_BAT_ICON                              76
#define LANG_OSD_LAYOUT_EDITOR_BAT_TEXT                              77
#define LANG_OSD_LAYOUT_EDITOR_CLOCK                                 78
#define LANG_PALETTE_TEXT_1                                          79
#define LANG_PALETTE_TEXT_2                                          80
#define LANG_PALETTE_TEXT_COLOR                                      81
#define LANG_PALETTE_TEXT_SELECT_COLOR                               82
#define LANG_CONSOLE_TEXT_INTERRUPTED                                83
#define LANG_CONSOLE_TEXT_FINISHED                                   84
#define LANG_BROWSER_ERASE_DIR_TITLE                                 85
#define LANG_BROWSER_ERASE_DIR_TEXT                                  86
#define LANG_BROWSER_DELETE_FILE_TITLE                               87
#define LANG_BROWSER_DELETE_FILE_TEXT                                88
#define LANG_MENU_MISC_DISABLE_LCD_OFF                               89
#define LANG_POPUP_CUT                                               90
#define LANG_POPUP_COPY                                              91
#define LANG_POPUP_PASTE                                             92
#define LANG_POPUP_DELETE                                            93
#define LANG_POPUP_SELINV                                            94
#define LANG_FSELECT_CUT_TITLE                                       95
#define LANG_FSELECT_CUT_TEXT                                        96
#define LANG_FSELECT_COPY_TITLE                                      97
#define LANG_FSELECT_COPY_TEXT                                       98
#define LANG_FSELECT_DELETE_TITLE                                    99
#define LANG_FSELECT_DELETE_TEXT                                    100
#define LANG_FSELECT_PROGRESS_TITLE                                 101
#define LANG_MENU_SHOW_GRID                                         102
#define LANG_MENU_GRID_LOAD                                         103
#define LANG_MENU_GRID_TITLE                                        104
#define LANG_MENU_OSD_GRID_PARAMS                                   105
#define LANG_STR_SELECT_GRID_FILE                                   106
#define LANG_MENU_GRID_CURRENT                                      107
#define LANG_MENU_RAW_NOISE_REDUCTION                               108
#define LANG_MENU_GRID_FORCE_COLOR                                  109
#define LANG_MENU_GRID_COLOR_LINE                                   110
#define LANG_MENU_GRID_COLOR_FILL                                   111
#define LANG_MENU_OSD_CAM_SPACING                                   112
#define LANG_MENU_OSD_DEV_FACTOR                                    113
#define LANG_MENU_OSD_NEAR_FACTOR                                   114
#define LANG_MENU_OSD_MANUAL_SET_DIST                               115
#define LANG_MENU_OSD_VALUE_STEP_SIZE                                116
#define LANG_MENU_OSD_DISTANCE                                      117
#define LANG_MENU_OSD_SAVE_XML                                      118
#define LANG_MENU_OSD_CSV_WITH_JPEG                                 119
#define LANG_MENU_OSD_SPM_URL                                       120
#define LANG_MENU_OSD_STEREO_PARAM                                  121
#define LANG_MENU_OSD_FOCUS_MODE                                    122
#define LANG_MENU_OSD_LAYOUT                                        123
#define LANG_MENU_OSD_CAM_POSITION                                  124
#define LANG_MENU_OSD_CAM_ORIENTATION                               125
#define LANG_MENU_OSD_CAM_ROTATION                                  126
#define LANG_MENU_TV_BRACKET_VALUE                                  127
#define LANG_MENU_RAW_SHUTTER_OVERRIDE                              128
#define LANG_MENU_RAW_VIDEO_MODE                                    129
#define LANG_MENU_RAW_VIDEO_BITRATE                                 130
#define LANG_MENU_RAW_VIDEO_QUALITY                                 131
#define LANG_MENU_SCRIPT_AUTOSTART                                  132
#define LANG_MENU_SCRIPT_REMOTE_ENABLE                              133
#define LANG_MENU_OSD_SYNCH                                         134
#define LANG_MENU_SYNCH_STATUS                                      135
#define LANG_MENU_SYNCH_DELAY                                       136
#define LANG_MENU_SYNCH_DELAY_VALUE                                 137
#define LANG_MENU_RAW_AV_OVERRIDE                                   138
#define LANG_MENU_SYNC_STEP_SIZE                                    139
#define LANG_MENU_DIST_BRACKET_VALUE                                140
#define LANG_MENU_BRACKET_TYPE                                      141
#define LANG_MENU_SYNCH_DELAY_COARSE_VALUE                          142
#define LANG_MENU_SYNCH_TITLE                                       143
#define LANG_MENU_STEREO_TITLE                                      144
#define LANG_OSD_LAYOUT_EDITOR_STEREO                               145
#define LANG_OSD_LAYOUT_EDITOR_SYNCH                                146
#define LANG_MENU_SDM_CONFIG                                        147
#define LANG_SDM_RF_TITLE                                           148
#define LANG_MENU_FAR_DISTANCE                                      149
#define LANG_SDM_RF_NEAR                                            150
#define LANG_SDM_FOCUS_TEST_TITLE                                   151
#define LANG_SDM_FOCUS_TEST_FOCUSED                                 152
#define LANG_SDM_FOCUS_TEST_TO_SUBJECT                              153
#define LANG_SDM_FOCUS_TEST_TO_SENSOR                               154
#define LANG_MENU_OVERRIDE_ND_FILTER                                155
#define LANG_MENU_IMAGE_STACK                                       156
#define LANG_MENU_ON                                                157
#define LANG_MENU_OFF                                               158
#define LANG_LEFT_CAMERA                                            159
#define LANG_RIGHT_CAMERA                                           160
#define LANG_ENABLED                                                161
#define LANG_DISABLED                                               162
#define LANG_SELECT_INACTIVE                                        163
#define LANG_SELECT_FLASH                                           164
#define LANG_SELECT_MANUAL                                          165
#define LANG_MENU_ZEBRA_MULTICHANNEL                                166
#define LANG_MENU_INFINITY                                          167
#define LANG_MENU_HYPERFOCAL                                        168
#define LANG_MENU_ALTERNATE                                         169
#define LANG_MENU_SLOWER                                            170
#define LANG_MENU_FASTER                                            171
#define LANG_MENU_OUTWARDS                                          172
#define LANG_MENU_OPTICAL_ZOOM_IN_VIDEO                             173
#define LANG_MENU_OSD_STEREO_PLAYBACK                               174
#define LANG_MENU_DEBUG_SWAP_PART                                   175
#define LANG_ONLY_ONE_PARTITION                                     176
#define LANG_ERROR                                                  177
#define LANG_MENU_MUTE_ON_ZOOM                                      178
#define LANG_MENU_BASIC_TITLE                                       179
#define LANG_MENU_OVERRIDE                                          180
#define LANG_MENU_CREATIVE                                          181
#define LANG_MENU_IMAGE                                             182
#define LANG_MENU_VIDEO                                             183
#define LANG_MENU_IMAGE_VIDEO                                       184
#define LANG_MENU_RAW                                               185
#define LANG_MENU_TIMER_SYNCH                                       186
#define LANG_MENU_OSD_BRACKET_OVERRIDE                              187
#define LANG_MENU_SHUTTER_VALUE                                     188
#define LANG_MENU_ADD_SYNCH_DELAYS                                  189
#define LANG_MENU_ZOOM_ENABLE                                       190
#define LANG_MENU_ZOOM_TIMEOUT                                      191
#define LANG_MENU_DISABLE_DEVIATION_GUIDELINE                       192
#define LANG_MENU_ND_CONSTANT_EXPOSURE                              193
#define LANG_MENU_EXTEND_LENS                                       194
#define LANG_MENU_DIGI_OD                                           195
#define LANG_MENU_DIGI_FL                                           196
#define LANG_MENU_DIGI_EP_FL                                        197
#define LANG_MENU_MAIN_DIGISCOPE                                    198
#define LANG_MENU_DIGI_TITLE                                        199
#define LANG_MENU_DIGI_ZOOM_SETTING                                 200
#define LANG_MENU_DIGI_REF_DIST                                     201
#define LANG_MENU_DIGI_SAVE                                         202
#define LANG_MENU_DIST_MODE                                         203
#define LANG_DIGI_REPORT_1                                          204
#define LANG_DIGI_REPORT_2                                          205
#define LANG_DIGI_REPORT_3                                          206
#define LANG_DIGI_REPORT_4                                          207
#define LANG_DIGI_REPORT_5                                          208
#define LANG_DIGI_REPORT_6                                          209
#define LANG_DIGI_REPORT_7                                          210
#define LANG_DIGI_REPORT_8                                          211
#define LANG_DIGI_REPORT_9                                          212
#define LANG_DIGI_REPORT_10                                         213
#define LANG_DIGI_REPORT_11                                         214
#define LANG_DIGI_REPORT_12                                         215
#define LANG_MENU_COMPACT                                           216
#define LANG_MENU_OSD_THRESH                                        217
#define LANG_MENU_EDGE_OVERLAY_TITLE                                218
#define LANG_MENU_EDGE_OVERLAY_ENABLE                               219
#define LANG_MENU_EDGE_OVERLAY_TRESH                                220
#define LANG_MENU_EDGE_OVERLAY_COLOR                                221
#define LANG_MENU_EDGE_LOAD                                         222
#define LANG_MENU_EDGE_SAVE                                         223
#define LANG_MENU_EDGE_PLAY                                         224
#define LANG_MENU_EDGE_FREE                                         225
#define LANG_MENU_EDGE_ZOOM                                         226
#define LANG_MENU_EDGE_LOCK                                         227
#define LANG_MENU_MAIN_EXPERIMENTAL                                 228
#define LANG_MENU_SUNRISE                                           229
#define LANG_MENU_SUNRISE_TV96                                      230
#define LANG_MENU_SUNRISE_REPEATS                                   231
#define LANG_MENU_SUNRISE_SHOTS                                     232
#define LANG_MENU_SUNRISE_TITLE                                     233
#define LANG_MENU_SRB                                               234
#define LANG_MENU_SUNRISE_KF_1                                      235
#define LANG_MENU_SUNRISE_KF_2                                      236
#define LANG_MENU_SUNRISE_KF_3                                      237
#define LANG_MENU_SUNRISE_TV96_2                                    238
#define LANG_MENU_SUNRISE_TV96_3                                    239
#define LANG_MENU_EDGE_OVERLAY_OSD                                  240
#define LANG_MENU_SCRIPT_PARAM_SET                                  241
#define LANG_MENU_MAIN_SERIAL_COM                                   242
#define LANG_MENU_SC_TITLE                                          243
#define LANG_MENU_BIT_WIDTH                                         244
#define LANG_MENU_MSEC                                              245
#define LANG_MENU_OSD_INVERT_PLAY                                   246
#define LANG_OSD_LAYOUT_EDITOR_SIO                                  247
#define LANG_MENU_BKT                                               248
#define LANG_MENU_ENABLE_YAW_GUIDELINE                              249
#define LANG_MENU_YAW_DEGREES                                       250
#define LANG_MENU_DOUBLE_CLICK                                      251
#define LANG_MENU_USE_AF_LED                                        252
#define LANG_MENU_OSD_ZOOM_FONT_SIZE                                253
#define LANG_OSD_LAYOUT_EDITOR_ZOOM                                 254
#define LANG_OSD_LAYOUT_EDITOR_INCREMENT                            255
#define LANG_MENU_MISC_LOCKOUT_TIME                                 256
#define LANG_MENU_EXPOSURE_COMP                                     257
#define LANG_MENU_VIS_ZEBRA_UNDER                                   258
#define LANG_MENU_VIS_ZEBRA_OVER                                    259
#define LANG_MENU_MISC_SLAVE_FLASH                                  260
#define LANG_MENU_OSD_SAVED_FOCUS                                   261
#define LANG_MENU_BRIGHT_SCREEN                                     262
#define LANG_MENU_SIO                                               263
#define LANG_MENU_DISABLE_SIO                                       264
#define LANG_MENU_RAW_STRIP_MODE                                    265
#define LANG_MENU_RAW_STRIP_WIDTH                                   266
#define LANG_MENU_RAW_STRIP_IMAGES                                  267 
#define LANG_MENU_MAIN_SLITCAM                                      268
#define LANG_MENU_SLITCAM_TITLE                                     269
#define LANG_MENU_RAW_STRIP_OFFSET                                  270   
#define LANG_MENU_RAW_BLANK_JPG                                     271   
#define LANG_MENU_RAW_STRIP_360_IMAGES                              272  
#define LANG_MENU_RAW_STRIP_ROTATION                                273   
#define LANG_MENU_RAW_STRIP_VIEWING                                 274
#define LANG_MENU_SHORTCUT_LANG                                     275 
#define LANG_MENU_SHORTCUTS                                         276 
#define LANG_MENU_BURST_SHUTDOWN                                    277
#define LANG_MENU_MISC_CLICK_TIME                                   278
#define LANG_MENU_VIDEO_FRAME_COUNT                                 279
#define LANG_INFORMATION                                            280
#define LANG_SWAPPED                                                281
#define LANG_MENU_FAST_LAPSE_DELAY                                  282
#define LANG_MENU_FAST_FINE_TUNE					        283
#define LANG_MENU_FAST_ONE_MSEC_COUNT					  284
#define LANG_MENU_BURST_FRAME_COUNT						  285
#define LANG_MENU_SYNCH_TIMER                                       286
#define LANG_MENU_BRACKET_INTERSHOT_DELAY					  287
#define LANG_MENU_BRACKET							  288
#define LANG_MENU_OVERRIDES							  289
#define LANG_MENU_FASTLAPSE							  290
#define LANG_MENU_OSD_FASTLAPSE						  291
#define LANG_MENU_FASTLAPSE_ENABLE						  292
#define LANG_MENU_MOVIE_FINE_TUNE						  293
#define LANG_MENU_OSD_ZOOM_PERMANENT					  294
#define LANG_MENU_OSD_ZOOM_AND_DEPTH				        295
#define LANG_MENU_OSD_SHOW							  296
#define LANG_MENU_SYNCH_FLASH_DELAY_VALUE					  297
#define LANG_MENU_VIDEO_SYNCH							  298
#define LANG_MENU_SCRIPT2_TITLE 						  299
#define LANG_MENU_SCRIPT3_TITLE 						  300
#define LANG_MENU_SCRIPT2_SUB_TITLE 					  301
#define LANG_MENU_SCRIPT3_SUB_TITLE 					  302
#define LANG_MENU_USER_SHORTCUT						  303
#define LANG_MENU_HOTSHOE						        304
#define LANG_MENU_ISO_OVERRIDE						  305
#define LANG_MENU_PRECISION_SYNCH_FLASH					  306
#define LANG_MENU_NEAR_DISTANCE						  307
#define LANG_MENU_OSD_ANAGLYPH_BUTTON					  308
#define LANG_MENU_LEFT_FLASH							  309
#define LANG_MENU_FLASH								  310
#define LANG_MENU_TRIGGER						        311
#define LANG_MENU_ENABLE_AUTO_ROTATION					  312
#define LANG_MENU_ALT_MODE_SHORTCUT                                 313
#define LANG_MENU_PARAM_SET							  314


//-------------------------------------------------------------------
#define GUI_LANG_ITEMS                                              314

//-------------------------------------------------------------------
extern void gui_lang_init();

//-------------------------------------------------------------------
#endif
