#include "conf.h"
#include "lang.h"
#include "gui_lang.h"

//-------------------------------------------------------------------
static char* gui_lang_default = \
"  1 \"EasySettings   \"\n"
"  2 \"OSD parameters\"\n"
"  3 \"EasyModes    \"\n"
"  4 \"Visual settings\"\n"
"  5 \"Miscellaneous  \"\n"
"  6 \"Debug params   \"\n"
"  7 \"Reset options  \"\n"
"  8 \"< Back\"\n"
"  9 \"Save RAW + DNG header\"\n"
" 10 \"PC 10msec\"\n"
" 11 \"OSD\"\n"
" 12 \"Show RAW/EXP state\"\n"
" 13 \"Show misc values\"\n"
" 14 \"Zoom value\"\n"
" 15 \"Show clock\"\n"
" 16 \"OSD layout editor\"\n"
" 17 \"Battery parameters \"\n"
" 18 \"Show live histogram\"\n"
" 19 \"Histogram layout\"\n"
" 20 \"Histogram mode\"\n"
" 21 \"Show histogram over/under EXP\"\n"
" 22 \"Stereo calculations\"\n"
" 23 \"Stereo calculations ->\"\n"
" 24 \"Playback options \"\n"
" 25 \"Playback options ->\"\n"
" 26 \"Zebra mode\"\n"
" 27 \"UnderExposure thresh\"\n"
" 28 \"OverExposure thresh\"\n"
" 29 \"Restore original screen\"\n"
" 30 \"Restore OSD\"\n"
" 31 \"Draw over zebra\"\n"
" 32 \"EasyMode Script\"\n"
" 33 \"Load script from file...\"\n"
" 34 \"Shoot delay (.1s)\"\n"
" 35 \"Visual settings\"\n"
" 36 \"Language...\"\n"
" 37 \"OSD codepage\"\n"
" 38 \"Menu RBF font...\"\n"
" 39 \"Miscellaneous\"\n"
" 40 \"File browser\"\n"
" 41 \"Text file reader\"\n"
" 42 \"Show splash screen on load\"\n"
" 43 \"Use zoom buttons for MF\"\n"
" 44 \"User scripts button\"\n"
" 45 \"Debug\"\n"
" 46 \"Show PropCases\"\n"
" 47 \"PropCase page\"\n"
" 48 \"Show misc. values\"\n"
" 49 \"Battery\"\n"
" 50 \"Voltage MAX\"\n"
" 51 \"Voltage MIN\"\n"
" 52 \"25+ step\"\n"
" 53 \"Text file reader\"\n"
" 54 \"Open new file...\"\n"
" 55 \"Open last opened file\"\n"
" 56 \"Select RBF font\"\n"
" 57 \"Codepage\"\n"
" 58 \"Wrap by words\"\n"
" 59 \"Enable autoscroll\"\n"
" 60 \"Autoscroll delay (sec)\"\n"
" 61 \"*** Reset options ***\"\n"
" 62 \"SURE you want to reset\\noptions to default?\"\n"
" 63 \"File Browser\"\n"
" 64 \"Select script file\"\n"
" 65 \"Select text file\"\n"
" 66 \"Select RBF-font file\"\n"
" 67 \"Select language file\"\n"
" 68 \"Ok\"\n"
" 69 \"Yes\"\n"
" 70 \"No\"\n"
" 71 \"Cancel\"\n"
" 72 \"Histogram\"\n"
" 73 \"DOF calc\"\n"
" 74 \"RAW/EXP\"\n"
" 75 \"Misc values\"\n"
" 76 \"Batt icon\"\n"
" 77 \"Batt text\"\n"
" 78 \"Clock\"\n"
" 79  \" \"\n"
" 80  \" \"\n"
" 81  \" \"\n"
" 82  \" \"\n"
" 83 \" INTERRUPTED \"\n"
" 84 \" FINISHED \"\n"
" 85 \"*** Erase directory ***\"\n"
" 86 \"Are you SURE to delete\\nALL files from\\nselected directory?\"\n"
" 87 \"*** Delete file ***\"\n"
" 88 \"Are you SURE to delete\\nselected file?\"\n"
" 89 \"Disable LCD off\"\n"
" 90 \"Cut\"\n"
" 91 \"Copy\"\n"
" 92 \"Paste\"\n"
" 93 \"Delete\"\n"
" 94 \"Select inverse\"\n"
" 95 \"*** Cut files ***\"\n"
" 96 \"Are you SURE to cut\\n%d selected files\\nfrom %s/?\"\n"
" 97 \"*** Copy files ***\"\n"
" 98 \"Are you SURE to copy\\n%d selected files\\nfrom %s/?\"\n"
" 99 \"*** Delete files ***\"\n"
"100 \"Are you SURE to delete\\n%d selected files?\"\n"
"101 \"Please wait...\"\n"
"102 \"Show grid lines\"\n"
"103 \"Load grid from file...\"\n"
"104 \"Grid and Yaw lines\"\n"
"105 \"Grid and Yaw settings \"\n"
"106 \"Select grid file\"\n"
"107 \"Current grid\"\n"
"108 \"Noise reduction\"\n"
"109 \"Override grid colors\"\n"
"110 \"Line color\"\n"
"111 \"Fill color\"\n"
"112 \"Camera spacing (mm)\"\n"
"113 \"Deviation factor\"\n"
"114 \"Near-subject factor\"\n"
"115 \"Override focus\"\n"
"116 \"Menu value step-size\"\n"
"117 \"Set focused distance\"\n"
"118 \"Save XML File\"\n"
"119 \"Save XML with JPG\"\n"
"120 \"SPM from stereo.jpn.org/eng\"\n"
"121 \"Multicam Rigs\"\n"
"122 \"Focus setting\"\n"
"123 \"OSD Layout Option\"\n"
"124 \"Twin-Cam position\"\n"
"125 \"Cam orientation\"\n"
"126 \"Cam rotated\"\n"
"127 \"Tv bracket value\"\n"
"128 \"Override shutter\"\n"
"129 \"Video mode\"\n"
"130 \"Video bitrate\"\n"
"131 \"Video quality\"\n"
"132 \"Autostart\"\n"
"133 \"Disable PC connection\"\n"
"134 \"Synchronisation \"\n"
"135 \"Enable synch\"\n"
"136 \"Enable synch delay\"\n"
"137 \"Fine delay (0.1ms)\"\n"
"138 \"Override aperture\"\n"
"139 \"Sync step size\"\n"
"140 \"Focus step-size\"\n"
"141 \"Bracketing type\"\n"
"142 \"Coarse delay 0.1s\"\n"
"143 \"Synchronisation\"\n"
"144 \"Stereo\"\n"
"145 \"OSD displays\"\n"
"146 \"Synch\"\n"
"147 \"Show SDM Configuration\"\n"
"148 \"  RANGEFINDER  \"\n"
"149 \"Far distance\"\n"
"150 \"Near     \"\n"
"151 \"  FOCUS TEST   \"\n" 
"152 \"Focused @\"\n" 
"153 \"Subject @\"\n" 
"154 \"To sensor\"\n" 
"155 \"ND filter state\"\n"
"156 \"Get stack (near-to-far)\"\n"
"157 \"ON\"\n"
"158 \"OFF\"\n"
"159 \"LEFT camera \"\n"
"160 \"RIGHT camera\"\n"
"161 \"Enabled\"\n"
"162 \"Disabled\"\n"
"163 \"inactive\n"
"164 \"Flash\"\n"
"165 \"MANUAL\"\n"
"166 \"RGB zebra (overexp. only)\"\n"
"167 \"INFINITY\"\n"
"168 \"HYPERFOCAL\"\n"
"169 \"alternate\"\n"
"170 \"slower\"\n"
"171 \"faster\"\n"
"172 \"outwards\"\n"
"173 \"Enable optical zoom\"\n" 
"174 \"Playback mode\"\n" 
"175 \"Swap partitions\"\n"
"176 \"This card has only one partition.\"\n"
"177 \"Error\"\n"
"178 \"Mute during zooming\"\n" 
"179 \"SDM Basic Menu\"\n"
"180 \"Overrides\"\n"
"181 \"Creative\"\n"
"182 \"Zebra/Histogram\"\n"
"183 \"Video\"\n"
"184 \"Video/Raw\"\n"
"185 \"Raw\"\n"
"186 \"Custom timer synch\"\n"
"187 \"Bracketing/Overrides\"\n"
"188 \"Shutter value\"\n"
"189 \"Enable User delay\"\n"
"190 \"Synch Zoom\"\n"
"191 \"Zoom time-out\"\n"
"192 \"Disable deviation guideline\"\n"
"193 \"ND constant exposure\"\n"
"194 \"Extend Lens\"\n"
"195 \"Objective dia\"\n"
"196 \"Scope focal length\"\n"
"197 \"Eyepiece focal length\"\n"
"198 \"Digiscoping\"\n"
"199 \"Digiscope Data\"\n"
"200 \"Camera zoom setting\"\n"
"201 \"Focus distance step\"\n"
"202 \"Log values to file\"\n"
"203 \"Focus mode\"\n"
"204 \"Telescope fl\"\n"
"205 \"Telescope objective diameter\"\n"
"206 \"Eyepiece fl\"\n"
"207 \"Telescope magnification\"\n"
"208 \"Telescope Exit Pupil\"\n"
"209 \"Camera Entrance Pupil\"\n"
"210 \"Digiscope equivalent FL\"\n"
"211 \"Digiscope equivalent FL (35mm)\"\n"
"212 \"Camera Focal length\"\n"
"213 \"Camera aperture\"\n"
"214 \"Focused distances (from front of lens)\"\n"
"215 \"and step size\"\n"
"216 \"SDM Header\"\n"
"217 \"Edge Overlay \"\n"
"218 \"Edge overlay\"\n"
"219 \"Enable edge overlay\"\n"
"220 \"Edge overlay threshold\"\n"
"221 \"Edge overlay color\"\n"
"222 \"Load Edge Overlay\"\n"
"223 \"Save Edge Overlay\"\n"
"224 \"Enable in Play\"\n"
"225 \"Free internal Memory\"\n"
"226 \"Load+Set Zoom\"\n"
"227 \"Lock Edge Overlay\"\n"
"228 \"Experimental (Sunrise)\"\n"
"229 \"Sunrise mode\"\n"
"230 \"Phase 1 delta Tv96\"\n"
"231 \"Tv96 repeats\"\n"
"232 \"Total shots/frames\"\n"
"233 \"Sunrise Experimental\"\n"
"234 \"Burst mode\"\n"
"235 \"Phase 1 end frame\"\n"
"236 \"Phase 2 end frame\"\n"
"237 \"Phase 3 end frame\"\n"
"238 \"Phase 2 delta Tv96\"\n"
"239 \"Phase 3 delta Tv96\"\n"
"240 \"Show Overlay and OSD's\"\n"
"241 \"Parameters set\"\n"
"242 \"Serial Comms\"\n"
"243 \"Serial Comms Data\"\n"
"244 \"Unit pulse width (ms)\"\n"
"245 \"Tune msec value\"\n"
"246 \"Invert playback image\"\n"
"247 \"Serial I/O\"\n"
"248 \"Bracketing\"\n"
"249 \"Yaw guideline\"\n"
"250 \"Yaw angle\"\n"
"251 \"Focus-cancel mode\"\n"
"252 \"Use autofocus LED\"\n"
"253 \"Zoom font size\"\n"
"254 \"Zoom\"\n"
"255 \"Increment\"\n"
"256 \"USB lockout time\"\n"
"257 \"Flash exposure comp\"\n"
"258 \"Zebra Underexposure\"\n"
"259 \"Zebra Overexposure\"\n"
"260 \"Slave Flash\"\n"
"261 \"Saved focus (from lens)\"\n"
"262 \"Bright screen\"\n"
"263 \"Show serial I/O info\"\n"
"264 \"Disable Serial I/O\"\n"
"265 \"Stereo Slitcam mode\"\n"
"266 \"Width for slit-camera\"\n"
"267 \"Number of slit images\"\n"
"268 \"Stereo Slit Camera\"\n"
"269 \"Stereo Slit Camera\"\n"
"270 \"Strip offset\"\n"
"271 \"Save blank JPG\"\n"
"272 \"Images for 360 pano\"\n"
"273 \"Rotation distance\"\n"
"274 \"View eye-separation\"\n"
"274 \"Viewing circle diam\"\n"
"275 \"Shortcut file language\"\n"
"276 \"Shortcuts\"\n"
"277 \"Burst shutdown\"\n"
"278 \"Button click-time\"\n"
"279 \"Video frame count\"\n"
"280 \"Information\"\n"
"281 \"Swapped !\"\n"
"282 \"Interval (0.1 sec)\"\n"
"283 \"FastLapse tune\"\n"
"284 \"Count for 1 msec\"\n"
"285 \"Number of shots\"\n"
"286 \"Timer or Synch\"\n"
"287 \"Intershot delay (0.1 sec)\"\n"
"288 \"Multi-shot Bracketing\"\n"
"289 \"Single-shot Overrides\"\n"
"290 \"FastLapse\"\n"
"291 \"FastLapse synched interval/bracketing\"\n"
"292 \"Enable (Continuous mode)\"\n"
"293 \"Movie-synch tune\"\n"
"294 \"Zoom always shown\"\n"
"295 \"Zoom + depth\"\n"
"296 \"Show OSD\"\n"
"297 \"Synch flash delay\"\n"
"298 \"Video synch device\"\n"
"299 \"SDM Scripts\"\n"
"300 \"User Scripts\"\n"
"301 \"System Scripts\"\n"
"302 \"My Scripts\"\n"
"303 \"Disable User shortcut\"\n"
"304 \"Hotshoe override\"\n"
"305 \"ISO override (1-10,0000)\"\n"
"306 \"Use precision synch with flash\"\n"
"307 \"Near distance\"\n"
"308 \"Anaglyph button\"\n"
"309 \"Use dim for left flash\"\n"
"310 \"Flash\"\n"
"311 \"Trigger high/low\"\n"
"312 \"Enable auto rotation\"\n"
"313 \"ALT shortcut to User Scripts\"\n"
"314 \"Parameter set\"\n"
// **************************************************************************
;

//-------------------------------------------------------------------
void gui_lang_init() {
    lang_init(GUI_LANG_ITEMS);
    lang_load_from_mem(gui_lang_default);
    if (conf.lang_file && *conf.lang_file) {
        lang_load_from_file(conf.lang_file);
    }
}

//-------------------------------------------------------------------
